# Generated by Django 5.2.17 on 2026-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
