# Generated by Django 5.2.17 on 2026-09-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_company_invoice_seller_address_invoice_seller_gstin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
