# Generated by Django 5.2.17 on 2026-09-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
